# Generated by Django 5.0.6 on 2024-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('amount', models.CharField(max_length=30, null=True)),
                ('order_id', models.CharField(max_length=30, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
