# Generated by Django 5.0.2 on 2024-11-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_coffee_drink_option_coffee_phone_coffee_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='paid',
        ),
        migrations.AddField(
            model_name='coffee',
            name='payment_status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='drink_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
