# Generated by Django 5.0.2 on 2024-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_coffee_payment_status_remove_coffee_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='drink_option',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='order_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
